apiVersion: v1
kind: Service
metadata:
  name: user-management-svc
  namespace: PLACEHOLDER
spec:
  selector:
    app: user-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
