# user-management/.github/workflows/cd.yml
name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  deploy-staging:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Simulate Deploy to staging
        run: |
          echo "kubectl apply --validate=false -f k8s/deployment.yaml -n staging"
          echo "kubectl apply --validate=false -f k8s/service.yaml    -n staging"

  manual-approval:
    needs: deploy-staging
    runs-on: ubuntu-latest
    steps:
      - name: Await manual approval
        run: echo "Waiting for manual approval to proceed to production..."

  deploy-production:
    needs: manual-approval
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Simulate Deploy to production
        run: |
          echo "kubectl apply --validate=false -f k8s/deployment.yaml -n production"
          echo "kubectl apply --validate=false -f k8s/service.yaml    -n production"

      - name: Notify Slack (design only)
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"✅ user-management production’a deploy edildi."}' \
            ${{ secrets.SLACK_WEBHOOK_URL }}

  rollback-strategy:
    name: Rollback Strategy (docs)
    runs-on: ubuntu-latest
    steps:
      - name: Document Rollback Command
        run: |
          echo "Rollback komutu:"
          echo "kubectl rollout undo deployment/user-management -n production"
